type ViolentmonkeyAPI =
	| 'GM_info'
	| 'GM_getValue'
	| 'GM_getValues'
	| 'GM_setValue'
	| 'GM_setValues'
	| 'GM_deleteValue'
	| 'GM_deleteValues'
	| 'GM_listValues'
	| 'GM_addValueChangeListener'
	| 'GM_removeValueChangeListener'
	| 'GM_getResourceText'
	| 'GM_getResourceUrl'
	| 'GM_getResourceURL'
	| 'GM_addElement'
	| 'GM_addStyle'
	| 'GM_openInTab'
	| 'GM_registerMenuCommand'
	| 'GM_unregisterMenuCommand'
	| 'GM_notification'
	| 'GM_setClipboard'
	| 'GM_xmlhttpRequest'
	| 'GM_xmlHttpRequest'
	| 'GM_download'
	| 'GM.addStyle'
	| 'GM.addElement'
	| 'GM.registerMenuCommand'
	| 'GM.deleteValue'
	| 'GM.deleteValues'
	| 'GM.download'
	| 'GM.getResourceUrl'
	| 'GM.getResourceURL'
	| 'GM.getValue'
	| 'GM.getValues'
	| 'GM.info'
	| 'GM.listValues'
	| 'GM.notification'
	| 'GM.openInTab'
	| 'GM.setClipboard'
	| 'GM.setValue'
	| 'GM.setValues'
	| 'GM.xmlHttpRequest'

declare function GM_getValue<T>(name: string, defaultValue?: T): T
declare function GM_setValue(name: string, value: unknown): void
